### ISSUE TITLE
Feature request: parameter to change the font size

### ISSUE THREAD

**Issue by Zeioth** [cornerman/i3-easyfocus#28]
This should be something easy to change, since every screen resolution will require a different size.

**Comment by cornerman** [comment]
Hi there, that is a good point. The problem with resolution and font size would be properly fixed with #14 .

What you can do right now is to set a different font: `i3-easyfocus --font <font-name>`. Just setting the 

You can see the available fonts for X on your system with `xlsfont`. Just setting the font-size is not really possible as of now.
