### ISSUE TITLE
Different key order more ergonomic?

### ISSUE THREAD

**Issue by talwrii** [cornerman/i3-easyfocus#8]
`avy`, the equivalent mode to this in emacs, tries to use keys on the home row and under ones hand, if possible.

Its key order preference is something like: `a s d f j k l g h ...`. This can very easily be achieved by reordering the keys in `config.h`. Should this be the default?

**Comment by cornerman** [comment]
I like that idea, it makes more sense than alphabetical order. Feel free to submit a PR :)

**Comment by cornerman** [comment]
But with different keyboard layouts, this really shows that we need some kind of option for this. I see two options:

- Specify the whole key sequence in order: `--keys=a,b,c,d,e,...`
- or named profiles like `--keys=alphabetical|avy`

**Comment by mtalexan** [comment]
The second option for named profiles seems like it would be much easier to implement.  Otherwise you'll have to do a translation between the letters specified in the `--keys=` argument to the `XK_` constants, which sounds like a huge headache.  
Since everyone currently has to build from scratch anyway, it's not a huge burden to manually modify the config.h and rebuild if someone wants something as configurable as the first option.
